version: '3'

services:
  shortlyd-tests:
    build:
      context: .
      dockerfile: ./test/Dockerfile.test
    networks:
      - shortly-tests
    volumes:
      - $PWD:/src
    # depends_on:
    #   - redis

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/data
  #   restart: on-failure
  #   networks:
  #     - shortly-tests

networks:
  shortly-tests:
    driver: bridge

volumes:
  redis-data: