version: '3'

services:
  shortly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 6060:6060

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - shortly

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    depends_on:
      - shortly

  alertmanager:
      image: prom/alertmanager
      ports:
        - "9093:9093"
      restart: unless-stopped
      volumes:
        - "./prometheus:/config"
        - alertmanager-data:/data
      command: --config.file=/config/alertmanager.yml --log.level=debug
      depends_on:
        - shortly


volumes:
  grafana-data: 
  prometheus-data: 
  alertmanager-data: 