services:
  shortlyd:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GOCACHE: ${GOCACHE}
        GOMODCACHE: ${GOMODCACHE}
      platforms:
        - linux/amd64
    ports:
      - 8080:8080
      # - 6060:6060
    env_file: .env
    networks:
      - shortly-net
    depends_on:
      - mongodb

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - shortly-net
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp   # Agent (compact thrift protocol)
      - 16686:16686     # Jaeger UI
      - 4318:4318       # OpenTelemetry HTTP

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - 9090:9090
  #   restart: unless-stopped
  #   volumes:
  #     - ./deploy/prom:/etc/prometheus
  #     - prometheus-data:/prometheus
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - shortlyd
  #   networks:
  #     - shortly-net

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped
  #   volumes:
  #     - ./deploy/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  #     - grafana-data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - shortly-net

  # alertmanager:
  #     image: prom/alertmanager
  #     ports:
  #       - 9093:9093
  #     restart: unless-stopped
  #     volumes:
  #       - ./cmd/shortlyd/deploy/prom:/etc/prometheus
  #       - alertmanager-data:/data
  #     command: --config.file=/etc/prometheus/alertmanager.yml --log.level=debug
  #     depends_on:
  #       - shortly

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/data
  #   restart: on-failure
  #   networks:
  #     - shortly

  mongodb:
    image: mongo:latest
    networks:
      - shortly-net
    ports:
      - 27017:27017
    volumes:
      - shortly-mongodb-data:/data/db

networks:
  shortly-net:
    driver: bridge

volumes:
  grafana-data: 
  prometheus-data: 
  # alertmanager-data: 
  # redis-data:
  shortly-mongodb-data:

#     eyJhbGciOiJSUzI1NiIsImtpZCI6IndEQ3JsaFozTmh3T3ZPSkFoVzdQQlB0UkRGbVZzVFFHcjZsbm15QVc3eWsifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQxNzI4MDYxLCJpYXQiOjE3NDE3MjQ0NjEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZDcyNTNjMjItYTMxNS00NzljLWI0N2UtNDg2NGJkYjI0N2UyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJkYXNoYm9hcmQtYWRtaW4iLCJ1aWQiOiI5ZTdhYWE1Zi1hMzU3LTRkMTItOWIzNC1iODZmMjFiMDljNzcifX0sIm5iZiI6MTc0MTcyNDQ2MSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmVybmV0ZXMtZGFzaGJvYXJkOmRhc2hib2FyZC1hZG1pbiJ9.gM6qoOj9tf3tRPYdb1Pn14h_E9lR9wJwX4EmJEQ-43R7ShMOByHkoENvxJiefeJRlhppH97riFHfqFbk2gvoP7VY1anRtiUUQpAmR3_Gzf33aqeDtxY53go12QzTLwdSrai123mF_dh8N-6LoV_UFsZlum5nExQtxLu1BOM7tE03QSJUmhE0MwpAPAx8N6K0XdKx-Fiz-FuLr9ryw3pMpNZNHnGF0FkPnfse7Z5rWvmAh88TzlZVMzJkKJaTy2C40S1m3xY91K9rsUT_SvCWfMZcOXJdoUE18HOvIskQjUrGMrrtN_UvJDJYqu1VFs72jDErFDn1Gkkq1leAOEdRHg
# kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443
