services:
  shortlyd:
    build:
      context: .
      dockerfile: ./Dockerfile
      # args:
      #   GOCACHE: ${GOCACHE}
      #   GOMODCACHE: ${GOMODCACHE}
      platforms:
        - linux/amd64
    ports:
      - 8080:8080
      # - 6060:6060
    env_file: .env
    networks:
      - shortly-net
    depends_on:
      - mongodb

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - shortly-net
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp   # Agent (compact thrift protocol)
      - 16686:16686     # Jaeger UI
      - 4318:4318       # OpenTelemetry HTTP

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - 9090:9090
  #   restart: unless-stopped
  #   volumes:
  #     - ./deploy/prom:/etc/prometheus
  #     - prometheus-data:/prometheus
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - shortlyd
  #   networks:
  #     - shortly-net

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped
  #   volumes:
  #     - ./deploy/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  #     - grafana-data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - shortly-net

  # alertmanager:
  #     image: prom/alertmanager
  #     ports:
  #       - 9093:9093
  #     restart: unless-stopped
  #     volumes:
  #       - ./cmd/shortlyd/deploy/prom:/etc/prometheus
  #       - alertmanager-data:/data
  #     command: --config.file=/etc/prometheus/alertmanager.yml --log.level=debug
  #     depends_on:
  #       - shortly

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/data
  #   restart: on-failure
  #   networks:
  #     - shortly

  mongodb:
    image: mongo:latest
    networks:
      - shortly-net
    ports:
      - 27017:27017
    volumes:
      - shortly-mongodb-data:/data/db

networks:
  shortly-net:
    driver: bridge

volumes:
  grafana-data: 
  prometheus-data: 
  # alertmanager-data: 
  # redis-data:
  shortly-mongodb-data: