global:
  scrape_interval: 30s
  scrape_timeout: 15s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: shortly
    metrics_path: /metrics
    static_configs:
      - targets: [ 'shortly:6060' ]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

