name: 'ci'

on:
  push:
    branches: [dev]
  pull_request: 
    branches: [dev]

jobs:
  ci:
    runs-on: 'ubuntu-22.04'
    env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'Set up Go'
        uses: 'actions/setup-go@v4'
        with:
          go-version: '1.19'

      - name: 'Run lint'
        uses: 'golangci/golangci-lint-action@v3'
        with:
          version: v1.52

          only-new-issues: true

      - name: 'Test'
        run: 'go test -v ./...'

      - name: Run coverage
        run:  go test -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
